# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [75]:
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [76]:
print(np. __version__)
print(np.show_config()) 

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/happy/anaconda3/Library/include
    lib directory: C:/Users/happy/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  host:
  

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [77]:
a = np.random.randint(8,size=(2,3,5))



### 4. Print a.


In [78]:
print(a)


[[[0 3 4 2 7]
  [1 3 2 0 3]
  [0 7 3 4 4]]

 [[6 3 1 7 2]
  [0 0 0 1 2]
  [1 0 4 4 1]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [79]:
b = np.ones((5,2,3))



### 6. Print b.


In [80]:
print(b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [15]:
a.size == b.size


True


### 8. Are you able to add a and b? Why or why not?


In [81]:
print("a and b cannot be added to each other as is because of shape difference a.shape == b.shape is ")
{a.shape == b.shape}


a and b cannot be added to each other as is because of shape difference a.shape == b.shape is 


{False}



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [82]:

c = np.transpose(b, (1,2,0))
c.shape


(2, 3, 5)


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [83]:
d = a + c
print("a and c can be added to each other because they are of same shape a.shape == c.shape is ")
print(a.shape == c.shape)


a and c can be added to each other because they are of same shape a.shape == c.shape is 
True



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [84]:
print(a)
print(d)



[[[0 3 4 2 7]
  [1 3 2 0 3]
  [0 7 3 4 4]]

 [[6 3 1 7 2]
  [0 0 0 1 2]
  [1 0 4 4 1]]]
[[[1. 4. 5. 3. 8.]
  [2. 4. 3. 1. 4.]
  [1. 8. 4. 5. 5.]]

 [[7. 4. 2. 8. 3.]
  [1. 1. 1. 2. 3.]
  [2. 1. 5. 5. 2.]]]



### 12. Multiply a and c. Assign the result to e.


In [85]:
e = a * c



### 13. Does e equal to a? Why or why not?


In [86]:
print("e is equal to a because all elements of e and a are True when compared if equal")
e == a



e is equal to a because all elements of e and a are True when compared if equal


array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [87]:
d_max = np.max(d)
print("d_max is :", d_max)

d_min = np.min(d)
print("d_min is :", d_min)

d_mean = np.mean(d)
print("d_mean is :", d_mean)

d_max is : 8.0
d_min is : 1.0
d_mean is : 3.5



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [88]:
f = np.empty((2, 3, 5))
f.shape


(2, 3, 5)




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [90]:



f[d == d_min] = 0
f[(d > d_min) & (d < d_mean)] = 25
f[d == d_mean] = 50
f[(d > d_mean) & (d < d_max)] = 75
f[d == d_max] = 100







### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [91]:
print(d)
print (f)


[[[1. 4. 5. 3. 8.]
  [2. 4. 3. 1. 4.]
  [1. 8. 4. 5. 5.]]

 [[7. 4. 2. 8. 3.]
  [1. 1. 1. 2. 3.]
  [2. 1. 5. 5. 2.]]]
[[[  0.  75.  75.  25. 100.]
  [ 25.  75.  25.   0.  75.]
  [  0. 100.  75.  75.  75.]]

 [[ 75.  75.  25. 100.  25.]
  [  0.   0.   0.  25.  25.]
  [ 25.   0.  75.  75.  25.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [92]:

g = np.where( f == 0, "A", f)
g = np.where( f == 25, "B", g)
g = np.where( f == 50, "C", g)
g = np.where( f == 75, "D", g)
g = np.where( f == 100, "E", g)
print(g)


[[['A' 'D' 'D' 'B' 'E']
  ['B' 'D' 'B' 'A' 'D']
  ['A' 'E' 'D' 'D' 'D']]

 [['D' 'D' 'B' 'E' 'B']
  ['A' 'A' 'A' 'B' 'B']
  ['B' 'A' 'D' 'D' 'B']]]
